### ISSUE TITLE
No such host at :80

### ISSUE THREAD

**Issue by mrothenbuecher** [ubergesundheit/helpyio-docker#1]
Hi,

i started `sudo docker-compose up -d` and changed the portforwading (port 80,443 is already in use) and all started just fine.

```
          Name                        Command               State                       Ports
-----------------------------------------------------------------------------------------------------------------
helpyiodocker_frontend_1   caddy -conf /etc/caddy/Cad ...   Up      0.0.0.0:65001->443/tcp, 0.0.0.0:65000->80/tcp
helpyiodocker_helpy_1      ./run.sh                         Up
helpyiodocker_postgres_1   /docker-entrypoint.sh postgres   Up      5432/tcp
```

But i can't access helpy. Message is:

> No such host at :80

I guess I have edit the network interface in the frontend_1 but I don't know how.

**Comment by ubergesundheit** [comment]
Could you try the follwing?

The default domain for the caddy instance is `localhost.localdomain` (see [here](https://github.com/ubergesundheit/helpyio-docker/blob/master/Caddyfile#L1)

You have to replace `localhost.localdomain` with a domain you control

**Comment by mrothenbuecher** [comment]
I tried it but it didn't work, But I am not sure about my editing process.
1. `vim Caddyfile` --> `localhost.localdomain` to `*`
2. `sudo docker-compose stop`
3. `sudo docker-compose build`
4. `sudo docker-compose up -d`

**Comment by ubergesundheit** [comment]
what is the output of `docker-compose logs frontend` ?
docker-compose reuses previously created containers. You could try `docker-compose up --force-recreate`

**Comment by mrothenbuecher** [comment]
`0.0.0.0:80` in Caddyfile did the trick.
